### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by GracefulUni** [karkkant/valheim-spearfishing#5]
Can we get a config file for this mod? I would like to use this mod but I dont feel using a "Bow" really makes any sense for spearfishing, Spear and Harpoon are good choices, but I would like to turn off the Bow

**Comment by karkkant** [comment]
It should be possible to do, yes. But I don't know how useful that would be.

1) This is a client side mod so it only affects -your- client. You could simply decide not to use bow for fishing.

2) If you host a server and want to prevent everyone from using a bow, this would need to be changed into a server side mod as well and start syncing configs. Which is something I'd like to avoid to keep the mod optional.

**Comment by GracefulUni** [comment]
> It should be possible to do, yes. But I don't know how useful that would be.
> 
> 1. This is a client side mod so it only affects -your- client. You could simply decide not to use bow for fishing.
> 2. If you host a server and want to prevent everyone from using a bow, this would need to be changed into a server side mod as well and start syncing configs. Which is something I'd like to avoid to keep the mod optional.

Ah I see, yea its pretty much me wanting people to not use Bows for the fishing, i do love the mod and its well done, i just dont think Bows really makes sense here is all.

**Comment by Goldenrevolver** [comment]
just throwing in my two cents cause I just visited the other issue, bowfishing has a long history in human survival, tradition and sport. but I will admit that hitting a fish with a crossbow bolt or other projectiles would not leave anything edible

It still makes sense that you don't want it for flavor and balancing reasons in your video game of course, since bows are already op in valheim

**Comment by karkkant** [comment]
ServerSynced configs are finally added in v1.0.4.
